title: "REGRESSIN IN FOSSIL"
email: "your-email@example.com"
description: "We love fossils and Math! "
baseurl: "" # leave this blank unless you have a custom subdirectory
url: "https://your-username.github.io" # your GitHub repository URL

# Theme
theme: minima

# Plugins (for things like SEO tags and RSS feeds)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown

