title: "REGRESSIN IN FOSSIL"
email: "your-email@example.com"
description: "A simple Jekyll site using the Minima theme."
baseurl: "" # leave this blank unless you have a custom subdirectory
url: "https://your-username.github.io" # your GitHub repository URL

# Theme
theme: minima

# Plugins (for things like SEO tags and RSS feeds)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown

# Optional social links (replace with your accounts)
twitter_username: your-twitter-handle
github_username: your-github-username
